/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Herramientas.Validaciones;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author el_fr
 */
public class Paso2Proporciones extends javax.swing.JFrame {

    /**
     * Creates new form ViewMacrociclo
     */
    public Paso2Proporciones() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEncabezadoTitulo = new javax.swing.JPanel();
        lblTitulo1 = new javax.swing.JLabel();
        lblEncabezadoMacro = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblDeporte = new javax.swing.JLabel();
        lblRama = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblNum = new javax.swing.JLabel();
        lblGuion1 = new javax.swing.JLabel();
        lblGuion2 = new javax.swing.JLabel();
        lblArrow = new javax.swing.JLabel();
        btnConfigurarAcentos = new javax.swing.JButton();
        lblFechaFinMacro = new javax.swing.JLabel();
        lblSemanasMacro = new javax.swing.JLabel();
        lblMensajeMacro = new javax.swing.JLabel();
        txtNumSemanasMacro = new javax.swing.JTextField();
        txtFechaInicioMacro = new javax.swing.JTextField();
        txtFechaFinMacro = new javax.swing.JTextField();
        lblDuracionMacro = new javax.swing.JLabel();
        lblFechaInicioMacro = new javax.swing.JLabel();
        pnlPeriodos = new javax.swing.JPanel();
        txtNumSemanasPreparatorio = new javax.swing.JTextField();
        txtNumSemanasCompetitivo = new javax.swing.JTextField();
        txtPorcientoPreparatorio = new javax.swing.JTextField();
        txtPorcientoCompetitivo = new javax.swing.JTextField();
        lblPreparatorio = new javax.swing.JLabel();
        lblCompetitivo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblPorciento3 = new javax.swing.JLabel();
        lblPorciento5 = new javax.swing.JLabel();
        lblPorciento6 = new javax.swing.JLabel();
        lblPorciento7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlEtapas = new javax.swing.JPanel();
        txtNumSemanasGeneral = new javax.swing.JTextField();
        txtNumSemanasEspecial = new javax.swing.JTextField();
        txtPorcientoGeneral = new javax.swing.JTextField();
        txtPorcientoEspecial = new javax.swing.JTextField();
        lblPorciento = new javax.swing.JLabel();
        lblPorciento2 = new javax.swing.JLabel();
        lbltxt = new javax.swing.JLabel();
        lblEspecial = new javax.swing.JLabel();
        lblGeneral = new javax.swing.JLabel();
        lblPorciento1 = new javax.swing.JLabel();
        lblPorciento4 = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnCalcularPorcentajes = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nuevo Macrociclo");
        setBackground(new java.awt.Color(255, 255, 255));

        lblEncabezadoTitulo.setBackground(new java.awt.Color(98, 142, 255));
        lblEncabezadoTitulo.setPreferredSize(new java.awt.Dimension(750, 50));

        lblTitulo1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo1.setText("Paso #2: Seleccion de Proporciones");

        javax.swing.GroupLayout lblEncabezadoTituloLayout = new javax.swing.GroupLayout(lblEncabezadoTitulo);
        lblEncabezadoTitulo.setLayout(lblEncabezadoTituloLayout);
        lblEncabezadoTituloLayout.setHorizontalGroup(
            lblEncabezadoTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblEncabezadoTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lblEncabezadoTituloLayout.setVerticalGroup(
            lblEncabezadoTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblEncabezadoTituloLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblTitulo1)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        lblEncabezadoMacro.setBackground(new java.awt.Color(217, 217, 217));
        lblEncabezadoMacro.setPreferredSize(new java.awt.Dimension(750, 50));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setText("Nuevo Macrociclo");

        lblDeporte.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDeporte.setText("Deporte");

        lblRama.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblRama.setText("Rama");

        lblID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblID.setText("ID");

        lblNum.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNum.setText("#");

        lblGuion1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblGuion1.setText("-");

        lblGuion2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblGuion2.setText("-");

        javax.swing.GroupLayout lblEncabezadoMacroLayout = new javax.swing.GroupLayout(lblEncabezadoMacro);
        lblEncabezadoMacro.setLayout(lblEncabezadoMacroLayout);
        lblEncabezadoMacroLayout.setHorizontalGroup(
            lblEncabezadoMacroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblEncabezadoMacroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addComponent(lblDeporte)
                .addGap(32, 32, 32)
                .addComponent(lblGuion1)
                .addGap(35, 35, 35)
                .addComponent(lblRama)
                .addGap(37, 37, 37)
                .addComponent(lblGuion2)
                .addGap(35, 35, 35)
                .addComponent(lblNum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblID)
                .addGap(39, 39, 39))
        );
        lblEncabezadoMacroLayout.setVerticalGroup(
            lblEncabezadoMacroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblEncabezadoMacroLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(lblEncabezadoMacroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblEncabezadoMacroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDeporte)
                        .addComponent(lblRama)
                        .addComponent(lblID)
                        .addComponent(lblNum)
                        .addComponent(lblGuion1)
                        .addComponent(lblGuion2))
                    .addComponent(lblTitulo))
                .addContainerGap())
        );

        lblArrow.setText("<----");

        btnConfigurarAcentos.setBackground(new java.awt.Color(204, 255, 204));
        btnConfigurarAcentos.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        btnConfigurarAcentos.setText("Siguiente");
        btnConfigurarAcentos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfigurarAcentos.setOpaque(true);
        btnConfigurarAcentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigurarAcentosActionPerformed(evt);
            }
        });

        lblFechaFinMacro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFechaFinMacro.setText("Fecha Fin:");

        lblSemanasMacro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSemanasMacro.setText("Semanas");

        txtNumSemanasMacro.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNumSemanasMacro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumSemanasMacroKeyPressed(evt);
            }
        });

        txtFechaInicioMacro.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtFechaInicioMacro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFechaInicioMacroKeyPressed(evt);
            }
        });

        txtFechaFinMacro.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtFechaFinMacro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaFinMacroActionPerformed(evt);
            }
        });
        txtFechaFinMacro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFechaFinMacroKeyPressed(evt);
            }
        });

        lblDuracionMacro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDuracionMacro.setText("Duracion:");

        lblFechaInicioMacro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFechaInicioMacro.setText("Fecha Incio:");

        txtNumSemanasPreparatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumSemanasPreparatorioActionPerformed(evt);
            }
        });
        txtNumSemanasPreparatorio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumSemanasPreparatorioKeyPressed(evt);
            }
        });

        txtNumSemanasCompetitivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumSemanasCompetitivoKeyPressed(evt);
            }
        });

        txtPorcientoPreparatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPorcientoPreparatorioActionPerformed(evt);
            }
        });
        txtPorcientoPreparatorio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPorcientoPreparatorioKeyPressed(evt);
            }
        });

        txtPorcientoCompetitivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPorcientoCompetitivoKeyPressed(evt);
            }
        });

        lblPreparatorio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPreparatorio.setText("Preparatorio:");

        lblCompetitivo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCompetitivo.setText("Competitivo:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Seleccione la proporción que se");

        lblPorciento3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPorciento3.setText("semanas");

        lblPorciento5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPorciento5.setText("semanas");

        lblPorciento6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPorciento6.setText("% ");

        lblPorciento7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPorciento7.setText("% ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("le asignará a cada periodo:");

        javax.swing.GroupLayout pnlPeriodosLayout = new javax.swing.GroupLayout(pnlPeriodos);
        pnlPeriodos.setLayout(pnlPeriodosLayout);
        pnlPeriodosLayout.setHorizontalGroup(
            pnlPeriodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPeriodosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlPeriodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPeriodosLayout.createSequentialGroup()
                        .addGroup(pnlPeriodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPeriodosLayout.createSequentialGroup()
                                .addComponent(lblPreparatorio)
                                .addGap(11, 11, 11)
                                .addComponent(txtPorcientoPreparatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPeriodosLayout.createSequentialGroup()
                                .addComponent(lblCompetitivo)
                                .addGap(18, 18, 18)
                                .addComponent(txtPorcientoCompetitivo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPeriodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPeriodosLayout.createSequentialGroup()
                                .addComponent(lblPorciento7)
                                .addGap(12, 12, 12)
                                .addComponent(txtNumSemanasPreparatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlPeriodosLayout.createSequentialGroup()
                                .addComponent(lblPorciento6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNumSemanasCompetitivo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPeriodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPorciento5)
                            .addComponent(lblPorciento3))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPeriodosLayout.createSequentialGroup()
                        .addGroup(pnlPeriodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))))
        );
        pnlPeriodosLayout.setVerticalGroup(
            pnlPeriodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPeriodosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPeriodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumSemanasPreparatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPorcientoPreparatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPreparatorio)
                    .addComponent(lblPorciento3)
                    .addComponent(lblPorciento7))
                .addGap(18, 18, 18)
                .addGroup(pnlPeriodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumSemanasCompetitivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCompetitivo)
                    .addComponent(lblPorciento5)
                    .addComponent(lblPorciento6)
                    .addComponent(txtPorcientoCompetitivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlEtapas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtNumSemanasGeneral.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumSemanasGeneralKeyPressed(evt);
            }
        });

        txtNumSemanasEspecial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumSemanasEspecialKeyPressed(evt);
            }
        });

        txtPorcientoGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPorcientoGeneralActionPerformed(evt);
            }
        });
        txtPorcientoGeneral.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPorcientoGeneralKeyPressed(evt);
            }
        });

        txtPorcientoEspecial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPorcientoEspecialKeyPressed(evt);
            }
        });

        lblPorciento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPorciento.setText("semanas");

        lblPorciento2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPorciento2.setText("semanas");

        lbltxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbltxt.setText("Etapas del periodo Preparatorio ");

        lblEspecial.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEspecial.setText("Especial");

        lblGeneral.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblGeneral.setText("General");

        lblPorciento1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPorciento1.setText("%");

        lblPorciento4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPorciento4.setText("%");

        javax.swing.GroupLayout pnlEtapasLayout = new javax.swing.GroupLayout(pnlEtapas);
        pnlEtapas.setLayout(pnlEtapasLayout);
        pnlEtapasLayout.setHorizontalGroup(
            pnlEtapasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEtapasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlEtapasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGeneral)
                    .addComponent(lbltxt)
                    .addGroup(pnlEtapasLayout.createSequentialGroup()
                        .addGroup(pnlEtapasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEspecial)
                            .addComponent(txtPorcientoEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPorcientoGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(pnlEtapasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPorciento1)
                            .addComponent(lblPorciento4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlEtapasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlEtapasLayout.createSequentialGroup()
                                .addComponent(txtNumSemanasGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPorciento))
                            .addGroup(pnlEtapasLayout.createSequentialGroup()
                                .addComponent(txtNumSemanasEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPorciento2)))))
                .addGap(26, 26, 26))
        );
        pnlEtapasLayout.setVerticalGroup(
            pnlEtapasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEtapasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbltxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGeneral)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEtapasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPorcientoGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPorciento)
                    .addComponent(lblPorciento1)
                    .addComponent(txtNumSemanasGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(lblEspecial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEtapasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPorcientoEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPorciento2)
                    .addComponent(lblPorciento4)
                    .addComponent(txtNumSemanasEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnAtras.setBackground(new java.awt.Color(255, 153, 153));
        btnAtras.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        btnAtras.setText("Atrás");
        btnAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnSiguiente.setBackground(new java.awt.Color(237, 192, 123));
        btnSiguiente.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        btnSiguiente.setText("Configurar Acentos");
        btnSiguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSiguiente.setOpaque(true);
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnCalcularPorcentajes.setBackground(new java.awt.Color(51, 204, 255));
        btnCalcularPorcentajes.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        btnCalcularPorcentajes.setText("Calcular");
        btnCalcularPorcentajes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalcularPorcentajes.setOpaque(true);
        btnCalcularPorcentajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularPorcentajesActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Seleccione una fecha inicio ó una fecha fin");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblEncabezadoMacro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEncabezadoTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblMensajeMacro)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblFechaInicioMacro)
                            .addGap(16, 16, 16)
                            .addComponent(txtFechaInicioMacro, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(112, 112, 112)
                            .addComponent(lblDuracionMacro)
                            .addGap(12, 12, 12)
                            .addComponent(txtNumSemanasMacro, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(14, 14, 14)
                            .addComponent(lblSemanasMacro))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(lblFechaFinMacro)
                            .addGap(18, 18, 18)
                            .addComponent(txtFechaFinMacro, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(520, 520, 520)
                            .addComponent(btnSiguiente))
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(pnlPeriodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblArrow)
                            .addGap(16, 16, 16)
                            .addComponent(pnlEtapas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(148, 148, 148)
                            .addComponent(btnCalcularPorcentajes))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnAtras)
                            .addGap(506, 506, 506)
                            .addComponent(btnConfigurarAcentos))))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEncabezadoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lblEncabezadoMacro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 121, Short.MAX_VALUE)
                        .addComponent(btnSiguiente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(lblMensajeMacro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblFechaInicioMacro))
                    .addComponent(txtFechaInicioMacro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDuracionMacro)
                    .addComponent(txtNumSemanasMacro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSemanasMacro))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaFinMacro)
                    .addComponent(txtFechaFinMacro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlPeriodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(67, 67, 67)
                            .addComponent(lblArrow))
                        .addComponent(pnlEtapas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCalcularPorcentajes)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfigurarAcentos)
                    .addComponent(btnAtras))
                .addGap(29, 29, 29))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFechaFinMacroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaFinMacroKeyPressed
        String fechaInicio = this.txtFechaInicioMacro.getText();
        String fechaFin = this.txtFechaFinMacro.getText();
        // validar si se a presionado enter
        if (evt.getKeyCode() != 10) {
            return;
        }
        try {
            // si se presiono enter se validan los textos de los jtextField
            Validaciones val = new Validaciones();
            val.isFechaAnterior(fechaInicio, fechaFin);
            if (!fechaInicio.equals("")) {
                val.isFechaValida(fechaInicio);
                Long numSemanas = val.calcPeriodo(fechaInicio, fechaFin);
                txtNumSemanasMacro.setText(numSemanas + "");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", 1);
        }
    }//GEN-LAST:event_txtFechaFinMacroKeyPressed

    
    
    private void txtFechaInicioMacroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaInicioMacroKeyPressed
        String fechaInicio = this.txtFechaInicioMacro.getText();
        String numSemanas = this.txtNumSemanasMacro.getText();
        // validar si se a presionado enter

        if (evt.getKeyCode() != 10) {
            return;
        }
        try {

            Validaciones val = new Validaciones();
            val.isNumSemanaValido(numSemanas, 32, 52);
            if (!fechaInicio.equals("")) {
                if (!val.isFechaValida(fechaInicio)) {
                }

                LocalDate fin = val.calcPeriodo(fechaInicio, Integer.valueOf(numSemanas));
                txtFechaFinMacro.setText(val.convertirFecha(fin));

            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", 1);
        }
    }//GEN-LAST:event_txtFechaInicioMacroKeyPressed
    private int calcularSemanas(int total, int can){
        int re= (can*total)/100;
        return re;
    }
    private double calcularPorcentaje(int total, int can){
        double re= (can*100)/total;
        return re;
    }
    
    private String rellenarPorcentaje(String valor){
        
        try {
            Validaciones val = new Validaciones();
            if (!valor.equals("")) {
                if (val.isPorcentajeValido(Double.parseDouble(valor))) {
                }
                if (val.isNegativo(Double.parseDouble(valor))) {
                }
                return ((100-Integer.parseInt(valor))+"");

            }
        
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", 1);
        }
        
        return ((100-Integer.parseInt(valor))+"");
    }
    private String rellenarSemanas(String valor, String total){
        
        try {
            Validaciones val = new Validaciones();
            if (!valor.equals("")) {
                return ((Integer.parseInt(total)-Integer.parseInt(valor))+"");
                if (val.isNegativo(Double.parseDouble(valor))) {
                }
                if (val.isMenor(Integer.parseInt(total), Integer.parseInt(valor))) {
                }

            }
        
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", 1);
        }
        
        return ((100-Integer.parseInt(valor))+"");
    }
    private void txtNumSemanasMacroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumSemanasMacroKeyPressed
        String fechaInicio = this.txtFechaInicioMacro.getText();
        String numSemanas = this.txtNumSemanasMacro.getText();
        if (evt.getKeyCode() != 10) {
            return;
        }
        try {
            Validaciones val = new Validaciones();
            if (!val.isNumSemanaValido(numSemanas, 32, 52));
            if (!fechaInicio.equals("")) {
                if (!val.isFechaValida(fechaInicio));

                LocalDate fin = val.calcPeriodo(fechaInicio, Integer.valueOf(numSemanas));
                txtFechaFinMacro.setText(val.convertirFecha(fin));

            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", 1);
        }

    }//GEN-LAST:event_txtNumSemanasMacroKeyPressed

    private void btnCalcularPorcentajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularPorcentajesActionPerformed
   

    }//GEN-LAST:event_btnCalcularPorcentajesActionPerformed

    private void btnConfigurarAcentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigurarAcentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfigurarAcentosActionPerformed

    private void txtPorcientoGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPorcientoGeneralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPorcientoGeneralActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void txtFechaFinMacroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaFinMacroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaFinMacroActionPerformed

    private void txtPorcientoGeneralKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPorcientoGeneralKeyPressed
        String numSemanas = this.txtNumSemanasPreparatorio.getText();
        String porPre = this.txtPorcientoGeneral.getText();
        
        // validar si se a presionado enter
        if (evt.getKeyCode() != 10) {
            return;
        }
        
        try {
            txtPorcientoEspecial.setText(rellenarPorcentaje(porPre));
            System.out.println("entra");
            if (!numSemanas.equals("")) {
                System.out.println(numSemanas);
                txtNumSemanasGeneral.setText(calcularSemanas(Integer.parseInt(numSemanas), Integer.parseInt(txtPorcientoGeneral.getText()))+"");
                txtNumSemanasEspecial.setText(calcularSemanas(Integer.parseInt(numSemanas), Integer.parseInt(txtPorcientoEspecial.getText()))+"");
        }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", 1);
        }
    }//GEN-LAST:event_txtPorcientoGeneralKeyPressed

    private void txtPorcientoEspecialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPorcientoEspecialKeyPressed
        String numSemanas = this.txtNumSemanasPreparatorio.getText();
        String porPre = this.txtPorcientoEspecial.getText();
        
        // validar si se a presionado enter
        if (evt.getKeyCode() != 10) {
            return;
        }
        
        try {
            txtPorcientoGeneral.setText(rellenarPorcentaje(porPre));
            if (!numSemanas.equals("")) {
                txtNumSemanasGeneral.setText(calcularSemanas(Integer.parseInt(numSemanas), Integer.parseInt(txtPorcientoGeneral.getText()))+"");
                txtNumSemanasEspecial.setText(calcularSemanas(Integer.parseInt(numSemanas), Integer.parseInt(txtPorcientoEspecial.getText()))+"");
        }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", 1);
        }
    }//GEN-LAST:event_txtPorcientoEspecialKeyPressed

    private void txtNumSemanasGeneralKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumSemanasGeneralKeyPressed
        String sem = this.txtNumSemanasGeneral.getText();
        String numSemanas = this.txtNumSemanasPreparatorio.getText();
        
        // validar si se a presionado enter
        if (evt.getKeyCode() != 10) {
            return;
        }
        try {
            txtNumSemanasEspecial.setText(rellenarSemanas(sem,numSemanas));
            if (!numSemanas.equals("")) {
                txtPorcientoGeneral.setText(calcularPorcentaje(Integer.parseInt(txtNumSemanasPreparatorio.getText()), Integer.parseInt(txtNumSemanasGeneral.getText()))+"");
                txtPorcientoEspecial.setText(calcularPorcentaje(Integer.parseInt(txtNumSemanasPreparatorio.getText()), Integer.parseInt(txtNumSemanasEspecial.getText()))+"");
        }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", 1);
        }
    }//GEN-LAST:event_txtNumSemanasGeneralKeyPressed

    private void txtNumSemanasEspecialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumSemanasEspecialKeyPressed
        String sem = this.txtNumSemanasEspecial.getText();
        String numSemanas = this.txtNumSemanasPreparatorio.getText();
        
        // validar si se a presionado enter
        if (evt.getKeyCode() != 10) {
            return;
        }
        try {
            txtNumSemanasGeneral.setText(rellenarSemanas(sem,numSemanas));
            if (!numSemanas.equals("")) {
                txtPorcientoGeneral.setText(calcularPorcentaje(Integer.parseInt(txtNumSemanasPreparatorio.getText()), Integer.parseInt(txtNumSemanasGeneral.getText()))+"");
                txtPorcientoEspecial.setText(calcularPorcentaje(Integer.parseInt(txtNumSemanasPreparatorio.getText()), Integer.parseInt(txtNumSemanasEspecial.getText()))+"");
        }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", 1);
        }
    }//GEN-LAST:event_txtNumSemanasEspecialKeyPressed

    private void txtPorcientoCompetitivoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPorcientoCompetitivoKeyPressed
        String porPre = this.txtPorcientoCompetitivo.getText();
        String numSemanas = this.txtNumSemanasMacro.getText();

        // validar si se a presionado enter
        if (evt.getKeyCode() != 10) {
            return;
        }

        try {
            txtPorcientoPreparatorio.setText(rellenarPorcentaje(porPre));
            if (!numSemanas.equals("")) {
                txtNumSemanasCompetitivo.setText(calcularSemanas(Integer.parseInt(txtNumSemanasMacro.getText()), Integer.parseInt(txtPorcientoCompetitivo.getText()))+"");
                txtNumSemanasPreparatorio.setText(calcularSemanas(Integer.parseInt(txtNumSemanasMacro.getText()), Integer.parseInt(txtPorcientoPreparatorio.getText()))+"");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", 1);
        }
    }//GEN-LAST:event_txtPorcientoCompetitivoKeyPressed

    private void txtPorcientoPreparatorioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPorcientoPreparatorioKeyPressed
        String porPre = this.txtPorcientoPreparatorio.getText();
        String numSemanas = this.txtNumSemanasMacro.getText();

        // validar si se a presionado enter
        if (evt.getKeyCode() != 10) {
            return;
        }
        try {
            txtPorcientoCompetitivo.setText(rellenarPorcentaje(porPre));
            if (!numSemanas.equals("")) {
                txtNumSemanasCompetitivo.setText(calcularSemanas(Integer.parseInt(txtNumSemanasMacro.getText()), Integer.parseInt(txtPorcientoCompetitivo.getText()))+"");
                txtNumSemanasPreparatorio.setText(calcularSemanas(Integer.parseInt(txtNumSemanasMacro.getText()), Integer.parseInt(txtPorcientoPreparatorio.getText()))+"");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", 1);
        }
    }//GEN-LAST:event_txtPorcientoPreparatorioKeyPressed

    private void txtPorcientoPreparatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPorcientoPreparatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPorcientoPreparatorioActionPerformed

    private void txtNumSemanasCompetitivoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumSemanasCompetitivoKeyPressed
        String sem = this.txtNumSemanasCompetitivo.getText();
        String numSemanas = this.txtNumSemanasMacro.getText();

        // validar si se a presionado enter
        if (evt.getKeyCode() != 10) {
            return;
        }
        try {
            txtNumSemanasPreparatorio.setText(rellenarSemanas(sem,numSemanas));
            if (!numSemanas.equals("")) {
                txtPorcientoCompetitivo.setText(calcularPorcentaje(Integer.parseInt(txtNumSemanasMacro.getText()), Integer.parseInt(txtNumSemanasCompetitivo.getText()))+"");
                txtPorcientoPreparatorio.setText(calcularPorcentaje(Integer.parseInt(txtNumSemanasMacro.getText()), Integer.parseInt(txtNumSemanasPreparatorio.getText()))+"");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", 1);
        }
    }//GEN-LAST:event_txtNumSemanasCompetitivoKeyPressed

    private void txtNumSemanasPreparatorioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumSemanasPreparatorioKeyPressed
        String sem = this.txtNumSemanasPreparatorio.getText();
        String numSemanas = this.txtNumSemanasMacro.getText();

        // validar si se a presionado enter
        if (evt.getKeyCode() != 10) {
            return;
        }
        try {
            txtNumSemanasCompetitivo.setText(rellenarSemanas(sem,numSemanas));
            if (!numSemanas.equals("")) {
                txtPorcientoCompetitivo.setText(calcularPorcentaje(Integer.parseInt(txtNumSemanasMacro.getText()), Integer.parseInt(txtNumSemanasCompetitivo.getText()))+"");
                txtPorcientoPreparatorio.setText(calcularPorcentaje(Integer.parseInt(txtNumSemanasMacro.getText()), Integer.parseInt(txtNumSemanasPreparatorio.getText()))+"");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", 1);
        }
    }//GEN-LAST:event_txtNumSemanasPreparatorioKeyPressed

    private void txtNumSemanasPreparatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumSemanasPreparatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumSemanasPreparatorioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnCalcularPorcentajes;
    private javax.swing.JButton btnConfigurarAcentos;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblArrow;
    private javax.swing.JLabel lblCompetitivo;
    private javax.swing.JLabel lblDeporte;
    private javax.swing.JLabel lblDuracionMacro;
    private javax.swing.JPanel lblEncabezadoMacro;
    private javax.swing.JPanel lblEncabezadoTitulo;
    private javax.swing.JLabel lblEspecial;
    private javax.swing.JLabel lblFechaFinMacro;
    private javax.swing.JLabel lblFechaInicioMacro;
    private javax.swing.JLabel lblGeneral;
    private javax.swing.JLabel lblGuion1;
    private javax.swing.JLabel lblGuion2;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblMensajeMacro;
    private javax.swing.JLabel lblNum;
    private javax.swing.JLabel lblPorciento;
    private javax.swing.JLabel lblPorciento1;
    private javax.swing.JLabel lblPorciento2;
    private javax.swing.JLabel lblPorciento3;
    private javax.swing.JLabel lblPorciento4;
    private javax.swing.JLabel lblPorciento5;
    private javax.swing.JLabel lblPorciento6;
    private javax.swing.JLabel lblPorciento7;
    private javax.swing.JLabel lblPreparatorio;
    private javax.swing.JLabel lblRama;
    private javax.swing.JLabel lblSemanasMacro;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lbltxt;
    private javax.swing.JPanel pnlEtapas;
    private javax.swing.JPanel pnlPeriodos;
    private javax.swing.JTextField txtFechaFinMacro;
    private javax.swing.JTextField txtFechaInicioMacro;
    private javax.swing.JTextField txtNumSemanasCompetitivo;
    private javax.swing.JTextField txtNumSemanasEspecial;
    private javax.swing.JTextField txtNumSemanasGeneral;
    private javax.swing.JTextField txtNumSemanasMacro;
    private javax.swing.JTextField txtNumSemanasPreparatorio;
    private javax.swing.JTextField txtPorcientoCompetitivo;
    private javax.swing.JTextField txtPorcientoEspecial;
    private javax.swing.JTextField txtPorcientoGeneral;
    private javax.swing.JTextField txtPorcientoPreparatorio;
    // End of variables declaration//GEN-END:variables
}
