/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.Entrenador;

import DAOs.AdministradorDAO;
import DAOs.EntrenadoresDAO;
import DAOs.MacrociclosDAO;
import Dominio.Administrador;
import Dominio.Entrenador;
import Dominio.Macrociclo;
import Enumeradores.Ramas;
import Herramientas.ComboBoxUtils;
import Herramientas.Fecha;
import Herramientas.Validaciones;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author brawun
 */
public class Paso1Registro extends javax.swing.JFrame {

    //Atributos
    Entrenador entrenador;
    EntrenadoresDAO EntrenadoresDAO = new EntrenadoresDAO("AppPlanU");
    MacrociclosDAO MacrociclosDAO = new MacrociclosDAO("AppPlanU");
    Validaciones Validaciones = new Validaciones();
    ComboBoxUtils ComboBoxUtils = new ComboBoxUtils();
    Fecha Fecha = new Fecha();

    /**
     * Creates new form RegistrarEntrenador
     */
    public Paso1Registro(Entrenador entrenador) throws Exception {
        this.entrenador = entrenador;
        initComponents();
        llenarComboBoxes();
        llenarTextos();
    }

    public void llenarTextos() {
        this.txtNombreEntrenador.setText(this.entrenador.getNombre() + " " + this.entrenador.getApellidoPaterno() + " " + this.entrenador.getApellidoMaterno());
    }

    public void llenarComboBoxes() throws Exception {
        // Se llena cbx Jefes de Rama
        ComboBoxUtils.llenarComboBox(this.cbxJefeRama, ComboBoxUtils.arregloJefes());
        ComboBoxUtils.actualizarComboBox(this.cbxJefeRama);
        // Se llena cbx Deportes
        ComboBoxUtils.llenarComboBox(this.cbxDeporte, ComboBoxUtils.arregloDeportes());
        // Se llena cbx Ramas
        ComboBoxUtils.llenarComboBox(this.cbxRama, ComboBoxUtils.arregloRamas());
        // Se llena cbx Preparadores Fisico
        ComboBoxUtils.llenarComboBox(this.cbxPreparador, ComboBoxUtils.arregloPreparadores());
        ComboBoxUtils.actualizarComboBox(this.cbxPreparador);
        // Se llena cbx Metodologos
        ComboBoxUtils.llenarComboBox(this.cbxMetodologo, ComboBoxUtils.arregloMetodologos());
    }

    // Método que convierte una cadena en un enum Rama
    public Ramas obtenerRamaDesdeTexto(String texto) {
        for (Ramas rama : Ramas.values()) {
            if (rama.name().equalsIgnoreCase(texto)) {
                return rama;
            }
        }
        return null; // Devolver null si no coincide con ninguna opción
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEncabezadoTitulo = new javax.swing.JPanel();
        lblTitulo1 = new javax.swing.JLabel();
        lblEncabezadoMacro = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblJefeRama = new javax.swing.JLabel();
        lblEntrenador = new javax.swing.JLabel();
        lblDeporte = new javax.swing.JLabel();
        lblRama = new javax.swing.JLabel();
        lblPreparador = new javax.swing.JLabel();
        lblIngreseDatos = new javax.swing.JLabel();
        lblMetodologo = new javax.swing.JLabel();
        txtNombreEntrenador = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        cbxJefeRama = new javax.swing.JComboBox<>();
        cbxDeporte = new javax.swing.JComboBox<>();
        cbxRama = new javax.swing.JComboBox<>();
        cbxPreparador = new javax.swing.JComboBox<>();
        cbxMetodologo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Reigstro de Macrociclo");

        lblEncabezadoTitulo.setBackground(new java.awt.Color(98, 142, 255));

        lblTitulo1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo1.setText("Paso #1: Registro del Macrociclo");

        javax.swing.GroupLayout lblEncabezadoTituloLayout = new javax.swing.GroupLayout(lblEncabezadoTitulo);
        lblEncabezadoTitulo.setLayout(lblEncabezadoTituloLayout);
        lblEncabezadoTituloLayout.setHorizontalGroup(
            lblEncabezadoTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblEncabezadoTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo1)
                .addContainerGap(206, Short.MAX_VALUE))
        );
        lblEncabezadoTituloLayout.setVerticalGroup(
            lblEncabezadoTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblEncabezadoTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        lblEncabezadoMacro.setBackground(new java.awt.Color(217, 217, 217));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setText("Nuevo Macrociclo");

        javax.swing.GroupLayout lblEncabezadoMacroLayout = new javax.swing.GroupLayout(lblEncabezadoMacro);
        lblEncabezadoMacro.setLayout(lblEncabezadoMacroLayout);
        lblEncabezadoMacroLayout.setHorizontalGroup(
            lblEncabezadoMacroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblEncabezadoMacroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lblEncabezadoMacroLayout.setVerticalGroup(
            lblEncabezadoMacroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblEncabezadoMacroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblJefeRama.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblJefeRama.setText("Jefe de Rama:");

        lblEntrenador.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEntrenador.setText("Entrenador:");

        lblDeporte.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDeporte.setText("Deporte:");

        lblRama.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRama.setText("Rama:");

        lblPreparador.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPreparador.setText("Preparador Físico:");

        lblIngreseDatos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIngreseDatos.setText("Ingrese los datos del macrociclo:");

        lblMetodologo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMetodologo.setText("Metodólogo:");

        txtNombreEntrenador.setEditable(false);
        txtNombreEntrenador.setText("Nombre Entrenador");
        txtNombreEntrenador.setToolTipText("Apellido Paterno del entrenador");

        btnCancelar.setBackground(new java.awt.Color(237, 123, 123));
        btnCancelar.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setOpaque(true);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(132, 237, 123));
        btnGuardar.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setOpaque(true);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEncabezadoTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblEncabezadoMacro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(lblIngreseDatos))
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(lblJefeRama)
                .addGap(6, 6, 6)
                .addComponent(cbxJefeRama, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(lblEntrenador)
                .addGap(6, 6, 6)
                .addComponent(txtNombreEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(lblDeporte)
                .addGap(6, 6, 6)
                .addComponent(cbxDeporte, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(lblRama)
                .addGap(6, 6, 6)
                .addComponent(cbxRama, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblPreparador)
                .addGap(6, 6, 6)
                .addComponent(cbxPreparador, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(lblMetodologo)
                .addGap(6, 6, 6)
                .addComponent(cbxMetodologo, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(378, 378, 378)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblEncabezadoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblEncabezadoMacro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(lblIngreseDatos)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJefeRama)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(cbxJefeRama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEntrenador)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtNombreEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDeporte)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(cbxDeporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRama)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(cbxRama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPreparador)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(cbxPreparador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMetodologo)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(cbxMetodologo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar)
                    .addComponent(btnGuardar)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        int i = JOptionPane.showConfirmDialog(this, "¿Seguro que desea cancelar el registro?", "Advertencia", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (i == JOptionPane.YES_OPTION) {
            this.dispose();
            try {
                new PanelEntrenador(this.entrenador).setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(Paso1Registro.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            this.setVisible(true);
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // Se registra el nuevo macrociclo en la base de datos segun los datos seleccionados en el los TextField
        Macrociclo macrociclo = MacrociclosDAO.registrarMacrociclo(new Macrociclo(
                this.cbxDeporte.getSelectedItem().toString(),
                this.cbxJefeRama.getSelectedItem().toString(),
                this.obtenerRamaDesdeTexto(this.cbxRama.getSelectedItem().toString()),
                this.cbxMetodologo.getSelectedItem().toString(),
                this.cbxPreparador.getSelectedItem().toString(),
                this.entrenador));
        // LOS CAMPOS DE FECHA SE TIENEN QUE GUARAR EN LA SIGUIENTE PANTALLA
        if (macrociclo.getId() != null) {
            JOptionPane.showMessageDialog(null, "Se registró exitosamente el macrociclo: " + macrociclo.getDeporte() + " - Rama: " + macrociclo.getRama().name() + " - Preparador Fisico: " + macrociclo.getPreparadorFisico() + "\n Continue al siguiente paso...", "Registro de entrenador exitoso", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            try {
                new Paso2Proporciones(this.entrenador, macrociclo).setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(Paso1Registro.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ocurrió un errror al querer registrar la cuenta de entrenador.", "¡Error interno!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbxDeporte;
    private javax.swing.JComboBox<String> cbxJefeRama;
    private javax.swing.JComboBox<String> cbxMetodologo;
    private javax.swing.JComboBox<String> cbxPreparador;
    private javax.swing.JComboBox<String> cbxRama;
    private javax.swing.JLabel lblDeporte;
    private javax.swing.JPanel lblEncabezadoMacro;
    private javax.swing.JPanel lblEncabezadoTitulo;
    private javax.swing.JLabel lblEntrenador;
    private javax.swing.JLabel lblIngreseDatos;
    private javax.swing.JLabel lblJefeRama;
    private javax.swing.JLabel lblMetodologo;
    private javax.swing.JLabel lblPreparador;
    private javax.swing.JLabel lblRama;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JTextField txtNombreEntrenador;
    // End of variables declaration//GEN-END:variables
}
