name: Test and Merge PR to main
on:
  pull_request:
    branches: 
      - test
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configurar JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Testing Maven
      run: mvn test --file pom.xml
      if: failure()
    - name: Close Pull
      uses: peter-evans/close-pull@v3
      with:
        pull-request-number: ${{ github.event.number }}
        comment: Auto-closing pull request
        delete-branch: true
      if: always()
   # si falla el test, no se hace el merge
    - name: Approve Pull Request
      uses: juliangruber/approve-pull-request-action@v1.1.1
      with:
        github-token: ${{ github.token }}
        number: ${{ github.event.number }}
    - name: Merge Pull Request
      uses: juliangruber/merge-pull-request-action@v1
      with:
        github-token: ${{ github.token}}
        number: ${{ github.event.number }}
        method: squash
          

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
